version: '3.0'
services:
  pg_twitter_follower:
    image: postgres:9.5
    container_name: pg_twitter_follower
    restart: always 
    environment:
      - POSTGRES_USER=
      - POSTGRES_PASSWORD=
      - POSTGRES_DB=
      - TZ=Asia/Tehran
    volumes:
        - /home/barkhordar/docker/volumes/pg_twitter_follower/postgres/:/var/lib/postgresql/data/
    ports:
      - "5434:5432"

  twitter_follower:
    image: twitter_follower:0.4-6
    container_name: twitter_follower
    environment:
    #   PostgreSQL Config
      - POSTGRES_USER=
      - POSTGRES_PASSWORD=
      - POSTGRES_DB=
      - POSTGRES_HOST=
      - POSTGRES_PORT=
    #   Config
      - BASE_URL=wss://api.bale.ai/v1/bots/
      - TOKEN=
      - CHECK_INTERVAL=300
      - MAX_FOLLOW_PER_ROUND=70
      - MAX_UN_FOLLOW_PER_ROUND=65
    #   Log config
      - USE_GRAYLOG=0
      - SOURCE=twitter_follower_source
      - GRAYLOG_HOST=
      - GRAYLOG_PORT=12201
      - LOG_LEVEL=10
      - LOG_FACILITY_NAME=twitter_follower_facility
      - MONITORING_HASH=
    depends_on:
     - pg_twitter_follower
    restart: always